DROP TABLE IF EXISTS public.brand CASCADE;
DROP SEQUENCE IF EXISTS brand_seq;

DROP TABLE IF EXISTS public.model CASCADE;
DROP SEQUENCE IF EXISTS model_seq;

DROP TABLE IF EXISTS public.car CASCADE;
DROP SEQUENCE IF EXISTS car_seq;